### ISSUE TITLE
Friends Cards Re-sizing

### ISSUE THREAD

**Issue by rosyming** [rosyming/Roots-of-the-Earth-Project-1#30]
The friend cards all seem to work, but what I've noticed is that they render at different sizes occasionally depending on the content.

- [ ] Resize the card to display at a certain size so that the left-floats work properly

**Comment by komalbatra** [comment]
I believe this is fixed now. Please check and let me know.

**Comment by rosyming** [comment]
Didn't seem to work.  I just up-ed the height of the cards to make them taller so they all should load equally.  This is more of a brute-force fix.  There seems to be a way in bootstrap, but the problem was that it kept making the cards too wide.  Fixed in pull request #52.
