### ISSUE TITLE
Content overflows "Your Matched Hero" card

### ISSUE THREAD

**Issue by rosyming** [rosyming/Roots-of-the-Earth-Project-1#33]
Content overflows "Your Matched Hero" card.  Need to resize the content so that it stays within the card container.

![screen shot 2018-10-08 at 5 50 31 pm](https://user-images.githubusercontent.com/41979276/46635516-c63ccc80-cb22-11e8-97b9-eb9420a1a341.png)

**Comment by komalbatra** [comment]
I have not been able to see anything in this card at all.
