### ISSUE TITLE
Text updates: Interesting questions and text

### ISSUE THREAD

**Issue by rosyming** [rosyming/Roots-of-the-Earth-Project-1#44]
- [x] New questions:
1.    Intelligence – Are people intimidated when they play against you at Trivial Pursuit (Not Intimidated – Very Intimidated)
2.    Speed – Are you the tortoise (slow and steady) or the hare (fast and wild)? (Tortoise – Hare)
3.    Combat – Are you a lover or a fighter? (Lover – Fighter)
4.     Durability - Can you take a lickin' and keep on tickin'? (Lickin - Tickin) 
5. Power - Do you usually get to watch what you want on Netflix? (No Chill --> Chill)
6.  Still thinking....

- [x] Adding this to Upload your Image section: "Every super hero has a hidden identity - Upload your identity"

- [x] Changing the "Upload Image" button to say "Upload Identity"

- [x] Can we change it to say "Image processed!" to "Identity processed"

**Comment by ShemikaKW** [comment]
Complete.

**Comment by rosyming** [comment]
Here's the last question: Strength: Are you the reigning arm wrestling champ? (Participant award - Belt holder)

**Comment by komalbatra** [comment]
Just saw this after I submitted my Pull request. We might get some conflicts here!

**Comment by rosyming** [comment]
I like it how it is!  I'll close for now.
